apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-datascience-launcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-datascience-launcher
  template:
    metadata:
      labels:
        app: kubernetes-datascience-launcher
    spec:
      containers:
      - image: databio/refgenieserver
        name: refgenieserver
        command: ["/bin/sh", "-c"]
        args:
         - apk add git -y;
           git clone https://github.com/alexander-manley/refgenieserver.git;
           refgenieserver serve -c refgenie.yaml;
          



---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-datascience-launcher
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "kubernetes-datascience-launcher"
    port: 80
  selector:
    app: kubernetes-datascience-launcher


