apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-datascience-launcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-datascience-launcher
  template:
    metadata:
      labels:
        app: kubernetes-datascience-launcher
    spec:
      containers:
      - image: lingdu0001/jamovi:0.0.1
        name: jamovi
        command: ["/bin/bash", "-c"]
        args:
         - /usr/bin/python3 -m jamovi.server 41337 --if=*;



---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-datascience-launcher
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "kubernetes-datascience-launcher"
    port: 41337
  selector:
    app: kubernetes-datascience-launcher


